### PR TITLE
Stop creating cloud accounts.

### PR DESCRIPTION
**Pull request by rob-baron**
Currently when a user logs into to atmosphere it will attempt to create a clould account.  At the MOC we create the cloud account so there is no need to do anything else.

For the general solution, that could be migrated into the cyverse upstream - this should be conditional on a flag in the settings/local.py - but we do not need to do this here and now.

### CODE REVIEW

**Review by knikolla — APPROVED** [review]

**Comment by xuhang57** [comment]
Please clean it up. Thanks.

**Review by xuhang57 — CHANGES_REQUESTED** [review]
Instead of just return None. I would suggest get rid of this function in the code base entirely.

**Review by knikolla — APPROVED** [review]

**Comment by rob-baron** [comment]
I have eliminated the function.  And yes there is a settings (AUTO_CREATE_ACCOUNT should be false), however, by eliminating the function, it makes setup easier.

**Comment by rob-baron** [comment]
I somehow make the same mistake with git (I pushed too many files), so this last push was to fix the previous one.

**Review by knikolla — APPROVED** [review]

**Review by xuhang57 — APPROVED** [review]

**Pull request merged**
